# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/say.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/say.proto',
  package='hello',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fproto/say.proto\x12\x05hello\"?\n\nSayRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\x08\x63hildren\x18\x02 \x03(\x0b\x32\x11.hello.SayRequest\"\x1e\n\x0bSayResponse\x12\x0f\n\x07message\x18\x01 \x01(\t24\n\x03Say\x12-\n\x04Send\x12\x11.hello.SayRequest\x1a\x12.hello.SayResponseb\x06proto3'
)




_SAYREQUEST = _descriptor.Descriptor(
  name='SayRequest',
  full_name='hello.SayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hello.SayRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='children', full_name='hello.SayRequest.children', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=89,
)


_SAYRESPONSE = _descriptor.Descriptor(
  name='SayResponse',
  full_name='hello.SayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='hello.SayResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=121,
)

_SAYREQUEST.fields_by_name['children'].message_type = _SAYREQUEST
DESCRIPTOR.message_types_by_name['SayRequest'] = _SAYREQUEST
DESCRIPTOR.message_types_by_name['SayResponse'] = _SAYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SayRequest = _reflection.GeneratedProtocolMessageType('SayRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAYREQUEST,
  '__module__' : 'proto.say_pb2'
  # @@protoc_insertion_point(class_scope:hello.SayRequest)
  })
_sym_db.RegisterMessage(SayRequest)

SayResponse = _reflection.GeneratedProtocolMessageType('SayResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAYRESPONSE,
  '__module__' : 'proto.say_pb2'
  # @@protoc_insertion_point(class_scope:hello.SayResponse)
  })
_sym_db.RegisterMessage(SayResponse)



_SAY = _descriptor.ServiceDescriptor(
  name='Say',
  full_name='hello.Say',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=123,
  serialized_end=175,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='hello.Say.Send',
    index=0,
    containing_service=None,
    input_type=_SAYREQUEST,
    output_type=_SAYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAY)

DESCRIPTOR.services_by_name['Say'] = _SAY

# @@protoc_insertion_point(module_scope)
